name: 'ArgoCD Application Updater'
description: 'Provide a description here'
author: 'hipages'
inputs:
  # repo-token:
  #   description: 'GitHub token being used to create pull requests.'
  #   required: true
  files:
    description: 'Files containing the application manifest'
    default: '.argocd**.y*ml'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
