name: 'ArgoCD Application Updater'
description: 'Automatically update ArgoCD application manifests via pull requests.'
author: 'hipages'
inputs:
  files:
    description: 'A comma seperated list of glob patterns of files containing the application manifests.'
    default: '.argocd**.y*ml'
    required: false
  dryrun:
    description: 'Enable dry-run to execute without applying changes.'
    default: 'false'
    required: false
  allrepos:
    description: 'If true, all repositories will be processed.'
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
