apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: argocd-app-updater-action
  description: Catalog entities for argocd-app-updater-action.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
