apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: argocd-app-updater-action
  description: Applications managed within the argocd-app-updater-action repo.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
