name: 'release'
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '15'
      - run: yarn install
      - run: npm run all
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update dist files"
          file_pattern: dist/*.js
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
